- name: "2.2.5 | Audit | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller - Before Remediation"
  become: false
  win_shell: |
      . C:\Windows\Temp\CIS_REMEDIATION\UserRightAssignment.ps1
      (Get-AccountsWithUserRight -Right SeMachineAccountPrivilege). Account
  register: user_rights_before
  vars:
    ansible_shell_type: powershell
  tags:
    - patch
    - audit 
  
- name: Debug users rights before
  debug: 
    var: user_rights_before

- name: Add action log to the list - No remediation required (Not Domain Controller Server)
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required, Not a Domain Controller'
      ] }}"
  vars:
    task_name: "2.2.5 | PATCH | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller"
  when:
      - not win2022cis_is_domain_controller
  tags:
    - patch
    - audit

- name: Add action log to the list - No remediation required (Domain Controller Server)
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required, Ensure Add workstations to domain is set to Administrators already set and Domain Controller'
      ] }}"
  vars:
    task_name: "2.2.5 | PATCH | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller"
  when:
      - win2022cis_is_domain_controller
      - ('Administrators' in user_rights_before.stdout)
  tags:
    - patch
    - audit

- name: Add action log to the list - Remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Remediation required, Ensure Add workstations to domain is set to Administrators not set and Domain Controller'
      ] }}"
  vars:
    task_name: "2.2.5 | PATCH | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller"
  when: 
      - win2022cis_is_domain_controller
      - (user_rights_before.stdout == "") or ('Administrators' not in user_rights_before.stdout)
  tags:
    - patch
    - audit

- name: "2.2.5 | PATCH | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller"
  block:
    
    - name: "2.2.5 | PATCH | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller - Update User Right"
      ansible.windows.win_user_right:
          name: SeMachineAccountPrivilege
          users: Administrators
          action: set
    
    - name: Add action log to the list - Update User Right 
      set_fact:
        log_content: "{{ log_content + [
          task_name, 
          'Updated User Right - SeMachineAccountPrivilege'
          ] }}"
      vars:
        task_name: "2.2.5 | PATCH | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller - Update User Right"

  when:
      - win22cis_rule_2_2_5
      - win2022cis_is_domain_controller
      - (user_rights_before.stdout == "") or ('Administrators' not in user_rights_before.stdout)
  tags:
      - patch

- name: "2.2.5 | Audit | Ensure Add workstations to domain is set to Administrators DC only | Domain Controller - After Remediation"
  become: false
  win_shell: |
      . C:\Windows\Temp\CIS_REMEDIATION\UserRightAssignment.ps1
      (Get-AccountsWithUserRight -Right SeMachineAccountPrivilege). Account
  register: user_rights_before
  vars:
    ansible_shell_type: powershell
  tags:
    - patch
    - audit 

- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      # output_check_hostname: "{{ inventory_hostname }}"
      # output_check_osname: "{{ ansible_os_name }}"
      # output_check_hosttype: "{{ ansible_windows_domain_role }}"
      output_check_id: "2.2.5"
      output_check_name: "Ensure Add workstations to domain is set to Administrators DC only | Domain Controller"
      output_check_status_before: "{{ 'PASS' if (win2022cis_is_domain_controller and 'Administrators' in user_rights_before.stdout) or (not win2022cis_is_domain_controller) else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if (win2022cis_is_domain_controller and 'Administrators' in user_rights_before.stdout) or (not win2022cis_is_domain_controller)  else 'FAIL' }}"
      output_check_comments: "{{ 'Need To Fix From Domain Controller' if win2022cis_is_domain_member else 'Fix for Member Server' if fix_member_server else '' }}"
  tags:
    - patch
    - audit