- name: "2.2.1 | Audit | Ensure Access Credential Manager as a trusted caller is set to No One - Before Remediation"
  become: false
  ansible.windows.win_shell: |
      . C:\Windows\Temp\CIS_REMEDIATION\UserRightAssignment.ps1
      (Get-AccountsWithUserRight -Right SeTrustedCredManAccessPrivilege). Account
  register: user_rights_before
  vars:
    ansible_shell_type: powershell
  tags:
    - patch
    - audit

- name: Debug users rights before
  debug: 
    var: user_rights_before

- name: Add action log to the list - No remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required, Access Credential Manager already set to No One'
      ] }}"
  vars:
    task_name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One"
  when: user_rights_before.stdout == ''
  tags:
    - patch
    - audit

- name: Add action log to the list - Remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Remediation required, Access Credential Manager not set to No One'
      ] }}"
  vars:
    task_name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One"
  when: user_rights_before.stdout != ''
  tags:
    - patch
    - audit 

# Reference: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html
- name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One"
  block:
  
    - name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One - Update User Right (Standalone)"
      ansible.windows.win_user_right:
        name: SeTrustedCredManAccessPrivilege
        users: []
        action: set
      when: 
        - win2022cis_is_standalone
        #users: #Can be set to an empty list with action=set to remove all accounts from the right.
    
    - name: Add action log to the list - Update User Right (Standalone) 
      set_fact:
        log_content: "{{ log_content + [
          task_name, 
          'Updated User Right (Standalone) - SeTrustedCredManAccessPrivilege'
          ] }}"
      vars:
        task_name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One - Updated User Right (Standalone)"
      when: 
        - win2022cis_is_standalone
      
    - name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One - Update User Right (Domain Controller)"
      ansible.windows.win_shell: |
        $text = "[Unicode]  
        Unicode=yes  
        [Version]  
        signature=`"`$CHICAGO$`"  
        Revision=1  
        [Privilege Rights]
        SeTrustedCredManAccessPrivilege =
        "  
  
        #Get domain controller to run all commands against  
        $dc = Get-ADDomainController  
  
        #Create new GPO
        $GPO = Get-GPO -Name "{{ cis_gpo }}"
        if ($GPO -eq $null) {
            Write-Output "GPO  {{ cis_gpo }}  not exist, creating it"
            $newGPO = New-GPO -Name "{{ cis_gpo }}" -Server $dc
            #Create new SecEdit directory in the GPO folder in SYSVOL  
            New-Item "\\$($dc.domain)\SYSVOL\$($dc.domain)\Policies\{$($newGPO.id)}\Machine\Microsoft\Windows NT\SecEdit" -ItemType Directory  
        } 
        else {
            Write-Output "GPO {{ cis_gpo }} exist"
            $newGPO = $GPO
        }

        #Create GptTmpl.inf file in SecEdit folder  
        $text | Out-File "\\$($dc.domain)\SYSVOL\$($dc.domain)\Policies\{$($newGPO.id)}\Machine\Microsoft\Windows NT\SecEdit\GptTmpl.inf"  

        #search 
        #Get-ADObject -Filter * -SearchBase "CN={$($newGPO.id.Guid.ToUpper())},CN=Policies,CN=System,$($dc.DefaultPartition)"

        #Set CSEs for new GPO - NB! otherwise settings won't be picked up by either the Group Policy Management console or the client https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpsb/55bb803e-b35f-4ce8-b558-4c1e92ad77a4  
        Set-ADObject "CN={$($newGPO.id.Guid.ToUpper())},CN=Policies,CN=System,$($dc.DefaultPartition)" -Replace @{gPCMachineExtensionNames="[{827D319E-6EAC-11D2-A4EA-00C04F79F83A}{803E14A0-B4FB-11D0-A0D0-00A0C90F574B}]"} -Server $dc  
  
        #Force AD to process new GPO  
        $newGPO | Set-GPRegistryValue -Key HKLM\SOFTWARE -ValueName "Default" -Value "" -Type String -Server $dc  
        $newGPO | Remove-GPRegistryValue -Key HKLM\SOFTWARE -ValueName "Default" -Server $dc 
      when: win2022cis_is_domain_controller

    - name: Add action log to the list - Update User Right (Domain Controller) 
      set_fact:
        log_content: "{{ log_content + [
          task_name, 
          'Updated User Right (Domain Controller) - SeTrustedCredManAccessPrivilege'
          ] }}"
      vars:
        task_name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One - Updated User Right (Domain Controller)"
      when: 
        - win2022cis_is_domain_controller
     
  when: 
      - win22cis_rule_2_2_1
      - user_rights_before.stdout != '' or fix_member_server
  tags:
      - patch

- name: "2.2.1 | Audit | Ensure Access Credential Manager as a trusted caller is set to No One - After Remediation"
  become: false
  ansible.windows.win_shell: |
      . C:\Windows\Temp\CIS_REMEDIATION\UserRightAssignment.ps1
      (Get-AccountsWithUserRight -Right SeTrustedCredManAccessPrivilege). Account
  register: user_rights_after
  vars:
    ansible_shell_type: powershell
  tags:
    - patch
    - audit 

- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      # output_check_hostname: "{{ inventory_hostname }}"
      # output_check_osname: "{{ ansible_os_name }}"
      # output_check_hosttype: "{{ ansible_windows_domain_role }}"
      output_check_id: "2.2.1"
      output_check_name: "Ensure Access Credential Manager as a trusted caller is set to No One"
      output_check_status_before: "{{ 'PASS' if user_rights_before.stdout == '' else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if user_rights_after.stdout == '' else 'FAIL' }}"
      output_check_comments: "{{ 'Need To Fix From Domain Controller' if win2022cis_is_domain_member else 'Fix for Member Server' if fix_member_server else '' }}"
  tags:
    - patch
    - audit