- name: audit "19.5.1.1"
  ansible.windows.win_reg_stat:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
      name: NoToastApplicationNotificationOnLockScreen
  loop: "{{ hku_loaded_list }}"
  register: audit_19_5_1_1

# Reference: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html
- name: "19.5.1.1 | PATCH |  Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
      name: NoToastApplicationNotificationOnLockScreen
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  notify: change_requires_reboot
  when:
      - win22cis_rule_19_5_1_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.5.1.1
      - patch
      - toast

- name: audit "19.5.1.1" again
  ansible.windows.win_reg_stat:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
      name: NoToastApplicationNotificationOnLockScreen
  loop: "{{ hku_loaded_list }}"
  register: audit_19_5_1_1_again

- name: write report
  # write to report if need a report.
  vars:
    ansible_shell_type: sh
