- name: audit "19.7.8.2"
  ansible.windows.win_reg_stat:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
      name: DisableThirdPartySuggestions
  loop: "{{ hku_loaded_list }}"
  register: audit_19_7_8_2
  

# Reference: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html
- name: "19.7.8.2 | PATCH | Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
      name: DisableThirdPartySuggestions
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  #notify: change_requires_reboot
  when:
      - win22cis_rule_19_7_8_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.8.2
      - patch
      - userrights

- name: audit "19.7.8.2" again
  ansible.windows.win_reg_stat:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
      name: DisableThirdPartySuggestions
  loop: "{{ hku_loaded_list }}"
  register: audit_19_7_8_2_again

- name: write report
  # write to report if need a report.
  vars:
    ansible_shell_type: sh
