- name: audit "19.7.5.2"
  ansible.windows.win_reg_stat:
      path: HKU:\{{ item }}\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
      name: ScanWithAntiVirus
  loop: "{{ hku_loaded_list }}"
  register: audit_19_7_5_2
  

# Reference: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html
- name: "19.7.5.2 | PATCH | Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
      name: ScanWithAntiVirus
      data: 3
      type: dword
  loop: "{{ hku_loaded_list }}"
  #notify: change_requires_reboot
  when:
      - win22cis_rule_19_7_5_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_19.7.5.2
      - patch
      - attachments

- name: audit "19.7.5.2" again
  ansible.windows.win_stat:
      path: HKU:\{{ item }}\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
      name: ScanWithAntiVirus
  loop: "{{ hku_loaded_list }}"
  register: audit_19_7_5_2_again

- name: write report
  # write to report if need a report.
  vars:
    ansible_shell_type: sh
