- name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0 - Before Remediation."
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_before}}"
  tags:
    - patch
    - audit

- name: Get Current Maximum Password Age value
  win_shell: Get-Content "{{win_access_settings_file_before}}" | findstr 'MaximumPasswordAge' | %{$_.split(' ')[2]}
  register: pwd_set_112_before
  tags:
    - patch
    - audit

- name: Debug Maximum Password Age value before
  debug: 
    var: pwd_set_112_before.stdout


- name: Add action log to the list - No remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required'
      ] }}"
  vars:
    task_name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0.'"
  when: (pwd_set_112_before.stdout|trim|int > 0) and (pwd_set_112_before.stdout|trim|int <= win22cis_maximum_password_age)
  tags:
    - patch
    - audit

- name: Add action log to the list - Remediation Required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Remediation required, Maximum password age is not set to 365 or is 0 '
      ] }}"
  vars:
    task_name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0.'"
  when: (pwd_set_112_before.stdout|trim|int >= 999) or (pwd_set_112_before.stdout|trim|int > win22cis_maximum_password_age) or (pwd_set_112_before.stdout|trim|int == 0)
  tags:
    - patch
    - audit


- name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0"
  block:

      - name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0 - Set Maximum Password Age Value."
        community.windows.win_security_policy:
            section: System Access
            key: MaximumPasswordAge
            value: "{{ win22cis_maximum_password_age }}"

      - name: Add action log to the list - Set Maximum Password Age Value
        set_fact:
          log_content: "{{ log_content + [
            task_name, 
            'Maximum Password Age set to 365 '
            ] }}"
        vars:
          task_name: "1.1.2 | PATCH | Ensure Maximum password age is set to 365 or fewer days but not 0 - Set Maximum Password Age Value'"

  when: (win22cis_rule_1_1_2) or (pwd_set_112_before.stdout|trim|int >= 999) or (pwd_set_111_before.stdout|trim|int > win22cis_maximum_password_age) or (pwd_set_112_before.stdout|trim|int == 0)
  tags:
      - patch


- name: Export Current Windows System Access Settings | After Remediation
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_after}}"


- name: "1.1.2 | AUDIT | Ensure Maximum password age is set to 365 or fewer days but not 0 - After Remediation"
  ansible.windows.win_shell: Get-Content "{{win_access_settings_file_after}}" | findstr 'MaximumPasswordAge' | %{$_.split(' ')[2]}
  register: pwd_set_112_after
  tags:
    - patch
    - audit


- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      output_check_id: "1.1.2"
      output_check_name: "Ensure Maximum password age is set to 365 or fewer days but not 0."
      output_check_status_before: "{{ 'PASS' if (pwd_set_112_before.stdout|trim|int <= 365) and (pwd_set_112_before.stdout|trim|int != 0)  else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if (pwd_set_112_after.stdout|trim|int <= 365) and (pwd_set_112_after.stdout|trim|int != 0) else 'FAIL' }}"
      output_check_comments: "{{ 'Need To Fix From Domain Controller' if win2022cis_is_domain_member else 'Fix for Member Server' if fix_member_server else '' }}"
  tags:
    - patch
    - audit
