- name: "1.1.5 | AUDIT | Ensure Password must meet complexity requirements is set to Enabled - Before Remediation."
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_before}}"
  tags:
    - patch
    - audit

- name: Get Current Password Complexity value
  win_shell: Get-Content "{{win_access_settings_file_before}}" | findstr 'PasswordComplexity' | %{$_.split(' ')[2]}
  register: pwd_set_115_before
  tags:
    - patch
    - audit


- name: Debug Password Complexity Value before
  debug: 
    var: pwd_set_115_before.stdout


- name: Add action log to the list - No remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required'
      ] }}"
  vars:
    task_name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled.'"
  when: pwd_set_115_before.stdout|trim|int == win22cis_password_complexity
  tags:
    - patch
    - audit


- name: Add action log to the list - Remediation Required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Remediation required, Password complexity requirement is set to Disabled. '
      ] }}"
  vars:
    task_name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled.'"
  when: pwd_set_115_before.stdout|trim|int != win22cis_password_complexity
  tags:
    - patch
    - audit


- name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled."
  block:

      - name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled - Set Password Complexity Value."
        community.windows.win_security_policy:
            section: System Access
            key: PasswordComplexity
            value: "{{ win22cis_password_complexity }}"

      - name: Add action log to the list - Set Password Complexity Value
        set_fact:
          log_content: "{{ log_content + [
            task_name, 
            'Password complexity value set to Enabled (1) '
            ] }}"
        vars:
          task_name: "1.1.5 | PATCH | Ensure Password must meet complexity requirements is set to Enabled - Set Password Complexity Value'"

  when:
      - win22cis_rule_1_1_5
      - pwd_set_115_before.stdout|trim|int != win22cis_password_complexity
  tags:
      - patch


- name: Export Current Windows System Access Settings | After Remediation
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_after}}"


- name: "1.1.5 | AUDIT | Ensure Password must meet complexity requirements is set to Enabled - After Remediation"
  ansible.windows.win_shell: Get-Content "{{win_access_settings_file_after}}" | findstr 'PasswordComplexity' | %{$_.split(' ')[2]}
  register: pwd_set_115_after
  tags:
    - patch
    - audit


- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      output_check_id: "1.1.5"
      output_check_name: "Ensure Password must meet complexity requirements is set to Enabled."
      output_check_status_before: "{{ 'PASS' if pwd_set_115_before.stdout|trim|int == 1 else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if pwd_set_115_after.stdout|trim|int == 1 else 'FAIL' }}"
      output_check_comments: "{{ 'Need To Fix From Domain Controller' if win2022cis_is_domain_member else 'Fix for Member Server' if fix_member_server else '' }}"
  tags:
    - patch
    - audit
