- name: "1.1.4 | AUDIT | Ensure Minimum password length is set to 14 or more characters - Before Remediation."
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_before}}"
  tags:
    - patch
    - audit

- name: Get Current Minimum Password Length value
  win_shell: Get-Content "{{win_access_settings_file_before}}" | findstr 'MinimumPasswordLength' | %{$_.split(' ')[2]}
  register: pwd_set_114_before
  tags:
    - patch
    - audit


- name: Debug Minimum Password Length Value before
  debug: 
    var: pwd_set_114_before.stdout


- name: Add action log to the list - No remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required'
      ] }}"
  vars:
    task_name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters.'"
  when: pwd_set_114_before.stdout|trim|int >= win22cis_minimum_password_length
  tags:
    - patch
    - audit


- name: Add action log to the list - Remediation Required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Remediation required, Minimum password length is not set to 14 or more passwords '
      ] }}"
  vars:
    task_name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters.'"
  when: pwd_set_114_before.stdout|trim|int < win22cis_minimum_password_length
  tags:
    - patch
    - audit


- name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters."
  block:

      - name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters - Set Minimum Password Length Value."
        community.windows.win_security_policy:
            section: System Access
            key: MinimumPasswordLength
            value: "{{ win22cis_minimum_password_length }}"

      - name: Add action log to the list - Set Minimum Password Length Value
        set_fact:
          log_content: "{{ log_content + [
            task_name, 
            'Minimum Password Length value set to 14 '
            ] }}"
        vars:
          task_name: "1.1.4 | PATCH | Ensure Minimum password length is set to 14 or more characters - Set Minimum Password Length Value'"

  when:
      - win22cis_rule_1_1_4
      - pwd_set_114_before.stdout|trim|int < win22cis_minimum_password_length
  tags:
      - patch

- name: Export Current Windows System Access Settings | After Remediation
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_after}}"


- name: "1.1.4 | AUDIT | Ensure Minimum password length is set to 14 or more characters - After Remediation"
  ansible.windows.win_shell: Get-Content "{{win_access_settings_file_after}}" | findstr 'MinimumPasswordLength' | %{$_.split(' ')[2]}
  register: pwd_set_114_after
  tags:
    - patch
    - audit


- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      output_check_id: "1.1.4"
      output_check_name: "Ensure Minimum password length is set to 14 or more characters."
      output_check_status_before: "{{ 'PASS' if pwd_set_114_before.stdout|trim|int >= 14 else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if pwd_set_114_after.stdout|trim|int >= 14 else 'FAIL' }}"
      output_check_comments: "{{ 'Need To Fix From Domain Controller' if win2022cis_is_domain_member else 'Fix for Member Server' if fix_member_server else '' }}"
  tags:
    - patch
    - audit
