- name: "1.1.1 | AUDIT | Ensure Enforce password history is set to 24 or more passwords - Before Remediation."
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_before}}"
  tags:
    - patch
    - audit

- name: Get Current Password History Size value
  win_shell: Get-Content "{{win_access_settings_file_before}}" | findstr 'PasswordHistorySize' | %{$_.split(' ')[2]}
  register: pwd_set_111_before
  tags:
    - patch
    - audit

- name: Debug Password History Value before
  debug: 
    var: pwd_set_111_before.stdout


- name: Add action log to the list - No remediation required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required'
      ] }}"
  vars:
    task_name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords.'"
  when: pwd_set_111_before.stdout|trim|int >= win22cis_max_passwords_saved
  tags:
    - patch
    - audit

- name: Add action log to the list - Remediation Required
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Remediation required, Password history value is not set to 24 or more passwords '
      ] }}"
  vars:
    task_name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords.'"
  when: pwd_set_111_before.stdout|trim|int < win22cis_max_passwords_saved
  tags:
    - patch
    - audit

- name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords."
  block:

      - name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords - Set Password History Value."
        community.windows.win_security_policy:
            section: System Access
            key: PasswordHistorySize
            value: "{{ win22cis_max_passwords_saved }}"

      - name: Add action log to the list - Set Password History Value
        set_fact:
          log_content: "{{ log_content + [
            task_name, 
            'Password history value set to 24 or more passwords '
            ] }}"
        vars:
          task_name: "1.1.1 | PATCH | Ensure Enforce password history is set to 24 or more passwords - Set Password History Value'"

  when:
      - win22cis_rule_1_1_1
      - pwd_set_111_before.stdout|trim|int < win22cis_max_passwords_saved
  tags:
      - patch


- name: Export Current Windows System Access Settings | After Remediation
  ansible.windows.win_shell: secedit /export /cfg "{{win_access_settings_file_after}}"


- name: "1.1.1 | AUDIT | Ensure Enforce password history is set to 24 or more passwords - After Remediation"
  ansible.windows.win_shell: Get-Content "{{win_access_settings_file_after}}" | findstr 'PasswordHistorySize' | %{$_.split(' ')[2]}
  register: pwd_set_111_after
  tags:
    - patch
    - audit


- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      output_check_id: "1.1.1"
      output_check_name: "Ensure Enforce password history is set to 24 or more passwords."
      output_check_status_before: "{{ 'PASS' if pwd_set_111_before.stdout | trim | int == 24 else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if pwd_set_111_after.stdout | trim | int == 24 else 'FAIL' }}"
      output_check_comments: "{{ 'Need To Fix From Domain Controller' if win2022cis_is_domain_member else 'Fix for Member Server' if fix_member_server else '' }}"
  tags:
    - patch
    - audit
