---

- name: Get current value of AllowSuggestedAppsInWindowsInkWorkspace
  win_reg_stat:
    path: HKLM:\\Software\\Policies\\Microsoft\\WindowsInkWorkspace
    name: AllowSuggestedAppsInWindowsInkWorkspace
    state: query
  register: AllowSuggestedAppsInWindowsInkWorkspace_value
  when:
      - win22cis_rule_18_10_80_1
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_18.10.80.1
      - patch
      - wik

- name: Add action log to the list
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'No remediation required'
      ] }}"
  vars:
    task_name: "18.10.80.1 | PATCH | Ensure Allow suggested apps in Windows Ink Workspace is set to Disabled"
  when: AllowSuggestedAppsInWindowsInkWorkspace_value == 0
  tags:
    - patch
    - audit

- name: Add action log to the list
  set_fact:
    log_content: "{{ log_content + [
      task_name, 
      'Run with tag audit'
      ] }}"
  vars:
    task_name: "18.10.80.1 | PATCH | Ensure Allow suggested apps in Windows Ink Workspace is set to Disabled"
  when:
    - "'audit' in ansible_run_tags"  
  tags:
    - audit

- name: Debug registered variable
  debug:
    var: AllowSuggestedAppsInWindowsInkWorkspace_value
  when:
      - win22cis_rule_18_10_80_1

- name: "18.10.80.1 | PATCH | Ensure Allow suggested apps in Windows Ink Workspace is set to Disabled"
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsInkWorkspace
      name: AllowSuggestedAppsInWindowsInkWorkspace
      data: 0
      type: dword
  when:
      - AllowSuggestedAppsInWindowsInkWorkspace_value == 1
      - win22cis_rule_18_10_80_1
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_18.10.80.1
      - patch
      - wik

- name: Get current value of AllowSuggestedAppsInWindowsInkWorkspace
  win_reg_stat:
    path: HKLM:\\Software\\Policies\\Microsoft\\WindowsInkWorkspace
    name: AllowSuggestedAppsInWindowsInkWorkspace
    state: query
  register: AllowSuggestedAppsInWindowsInkWorkspace_value_postremediation
  when:
      - win22cis_rule_18_10_80_1
  tags:
      - level2-domaincontroller
      - level2-memberserver
      - rule_18.10.80.1
      - patch
      - wik

- name: Debug registered variable
  debug:
    var: AllowSuggestedAppsInWindowsInkWorkspace_value_postremediation
  when:
      - win22cis_rule_18_10_80_1

- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      output_check_id: "18.10.80.1"
      output_check_name: "Ensure Allow suggested apps in Windows Ink Workspace is set to Disabled"
      output_check_status_before: "{{ 'PASS' if AllowSuggestedAppsInWindowsInkWorkspace_value == 0 else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if AllowSuggestedAppsInWindowsInkWorkspace_value_postremediation == 0 else 'FAIL' }}"
      output_check_comments: "{{ '' }}"
  tags:
    - patch
    - audit

