- name: Get current value of 'Allow user control over installs'
  win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\Installer
    name: EnableUserControl
  register: reg_result1810801
  when:
    - win22cis_rule_18_10_80_1
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.10.80.1
    - patch
    - wik

- name: Debug the current registry value
  debug:
    var: reg_result1810801
  when: win22cis_rule_18_10_80_1

- name: Add action log to the list
  set_fact:
    log_content: "{{ log_content + [task_name, 'No remediation required'] }}"
  vars:
    task_name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled'"
  when: reg_result1810801.exists and reg_result1810801.value|default(0) == 0 and not fix_member_server
  tags:
    - patch
    - audit

- name: Add action log to the list
  set_fact:
    log_content: "{{ log_content + [task_name, 'Run with tag audit'] }}"
  vars:
    task_name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled'"
  when: "'audit' in ansible_run_tags"
  tags:
    - audit

- name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled'"
  block:
    - name: Ensure registry path exists
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Installer
        name: EnableUserControl
        type: dword
        state: present

    - name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - Update Registry"
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Installer
        name: EnableUserControl
        data: 0
        type: dword
      register: task_18_10_80_1_1

    - name: Debug registry update result
      debug:
        var: task_18_10_80_1_1

    - name: Add action log to the list
      set_fact:
        log_content: "{{ log_content + [
          task_name, 
          'Updated Registry HKLM:\\Software\\Policies\\Microsoft\\Windows\\Installer\\EnableUserControl=0',
          task_18_10_80_1_1
          ] }}"
      vars:
        task_name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - Update Registry"

    - name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - Update GPO"
      win_shell: |
        Import-Module GroupPolicy
        $GPO = Get-GPO -Name "{{ cis_gpo }}"
        if ($GPO -eq $null) {
            Write-Output "GPO {{ cis_gpo }} not exist, creating it"
            New-GPO -Name "{{ cis_gpo }}"
        } else {
            Write-Output "GPO {{ cis_gpo }} exist"
        }
        $domainGPOName = (Get-GPO -Name "{{ cis_gpo }}").DisplayName
        Set-GPRegistryValue -Name $domainGPOName -Key "HKLM:\Software\Policies\Microsoft\Windows\Installer" -ValueName "EnableUserControl" -Type DWORD -Value 0
      register: task_18_10_80_1_2
      when: win2022cis_is_domain_controller

    - name: Debug GPO update result
      debug:
        var: task_18_10_80_1_2
      when: win2022cis_is_domain_controller

    - name: Add action log to the list
      set_fact:
        log_content: "{{ log_content + [
          task_name, 
          'Ensure 'Allow user control over installs' is set to 'Disabled' in GPO ' ~ cis_gpo,
          task_18_10_80_1_2
          ] }}"
      vars:
        task_name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - Update GPO"
      when: win2022cis_is_domain_controller

    - name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - Update Local Group Policy"
      win_shell: |
        C:\Windows\Temp\CIS_REMEDIATION\LGPO.exe /t C:\Windows\Temp\CIS_REMEDIATION\s18\s18.10.80.1.txt
      register: task_18_10_80_1_3
      when: win2022cis_is_standalone

    - name: Debug Local Group Policy update result
      debug:
        var: task_18_10_80_1_3
      when: win2022cis_is_standalone

    - name: Add action log to the list
      set_fact:
        log_content: "{{ log_content + [
          task_name, 
          'Ensure 'Allow user control over installs' is set to 'Disabled'',
          task_18_10_80_1_3
          ] }}"
      vars:
        task_name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - Update Local Group Policy"
      when: win2022cis_is_standalone
  when: not reg_result1810801.exists or reg_result1810801.value|default(0) != 0 or fix_member_server
  tags:
    - patch

- name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled' - After Remediation"
  win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\Installer
    name: EnableUserControl
  register: reg_result1810801_a
  tags:
    - patch
    - audit

- name: Debug the registry value after remediation
  debug:
    var: reg_result1810801_a

- name: Add check result to the list
  set_fact:
    report_content: "{{ report_content + [new_report_content] }}"
  vars:
    new_report_content:
      output_check_id: "18.10.80.1"
      output_check_name: "Ensure 'Allow user control over installs' is set to 'Disabled'"
      output_check_status_before: "{{ 'PASS' if reg_result1810801.exists and reg_result1810801.value|default(0) == 0  else 'FAIL' }}"
      output_check_status_after: "{{ 'PASS' if reg_result1810801_a.exists and reg_result1810801_a.value|default(0) == 0 else 'WARNING' if reg_result1810801_a.value|default(0) == 1 and reg_result1810801.value|default(0) != 0 and win2022cis_is_domain_member else 'FAIL' }}"
      output_check_comments: "{{ '' }}"
  tags:
    - patch
    - audit
